### ISSUE TITLE
API or "Fetch" hook

### ISSUE THREAD

**Issue by stevenmtaylor** [commitd/hooks#12]
Feature Request

I was wondering if a general useFetch or some API calling hook was a sensible idea. I feel its something that I constantly rewrite. The whole useAPI that then returns loading, error and the result.

General idea being it would be a useEffect that calls fetch on some url with parameters. Im not sure what the right level of granularity would be. (If it should be something like)

```ts
interface ApiResult<R>{
  result: R
  loading: boolean
  error?: string
}

useAPI<T,R>(url: string, type: "POST" | "GET", body?: T): ApiResult<R>
```

Or if its more sensible to split it into useGet or usePost etc (if there are too many arguments on fetch to have one hook)

**Comment by stuarthendren** [comment]
It's a good idea but I think I'd recomend using [`swr`](https://swr.vercel.app/) or if more configuration is needed `react-query`. 

It will handle a load of extra stuff for you, such as polling, refreshing in page activation, using cashed result until refreshed, local manipulation...

It might be better to add a set of standard fetcher functions that can easily be used with `swr`. I'll think on it.

**Comment by stuarthendren** [comment]
The other thing here is that rarely is POST a hook type of thing. You normally only want to call it on a specific action, not on every render of a component.

**Comment by stevenmtaylor** [comment]
Yeah thats a good point, I will check out that library.

Yeah I wasnt completely sure if it was a good hook idea or not, just came to mind as something I always find myself rewriting.
